//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APSWinForm.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APSWinForm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   고객 ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CUSTOMER_ID {
            get {
                return ResourceManager.GetString("CUSTOMER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수요정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DEMAND {
            get {
                return ResourceManager.GetString("DEMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수요 ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DEMAND_ID {
            get {
                return ResourceManager.GetString("DEMAND_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수량과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DEMAND_QTY {
            get {
                return ResourceManager.GetString("DEMAND_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수요버전과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DEMAND_VER {
            get {
                return ResourceManager.GetString("DEMAND_VER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기한과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DUE_DATE {
            get {
                return ResourceManager.GetString("DUE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   작업조건과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EQP_ARRANGE {
            get {
                return ResourceManager.GetString("EQP_ARRANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설비그룹과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EQP_GROUP {
            get {
                return ResourceManager.GetString("EQP_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설비 ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EQP_ID {
            get {
                return ResourceManager.GetString("EQP_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모델명과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EQP_MODEL {
            get {
                return ResourceManager.GetString("EQP_MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설비정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EQUIPMENT {
            get {
                return ResourceManager.GetString("EQUIPMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   라인 ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LINE_ID {
            get {
                return ResourceManager.GetString("LINE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   라인정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LINE_INFO {
            get {
                return ResourceManager.GetString("LINE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   라인이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LINE_NAME {
            get {
                return ResourceManager.GetString("LINE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   생산단위크기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LOT_SIZE {
            get {
                return ResourceManager.GetString("LOT_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   공정소요시간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PROC_TIME {
            get {
                return ResourceManager.GetString("PROC_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로세스 ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PROCESS_ID {
            get {
                return ResourceManager.GetString("PROCESS_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   제품정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PRODUCT {
            get {
                return ResourceManager.GetString("PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   제품 ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PRODUCT_ID {
            get {
                return ResourceManager.GetString("PRODUCT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   제품이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PRODUCT_NAME {
            get {
                return ResourceManager.GetString("PRODUCT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   제품타입과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PRODUCT_TYPE {
            get {
                return ResourceManager.GetString("PRODUCT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   교체준비시간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SETUP_TIME {
            get {
                return ResourceManager.GetString("SETUP_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현장 ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SITE_ID {
            get {
                return ResourceManager.GetString("SITE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   표준공정 ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STD_STEP_ID {
            get {
                return ResourceManager.GetString("STD_STEP_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   표준공정 정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STD_STEP_INFO {
            get {
                return ResourceManager.GetString("STD_STEP_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   표준공정이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STD_STEP_NAME {
            get {
                return ResourceManager.GetString("STD_STEP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   공정 ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STEP_ID {
            get {
                return ResourceManager.GetString("STEP_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   공정순서과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STEP_ROUTE {
            get {
                return ResourceManager.GetString("STEP_ROUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   공정순서과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STEP_SEQ {
            get {
                return ResourceManager.GetString("STEP_SEQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   공정준비시간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STEP_SETUP {
            get {
                return ResourceManager.GetString("STEP_SETUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   공정소요시간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STEP_TAT {
            get {
                return ResourceManager.GetString("STEP_TAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   공정타입과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STEP_TYPE {
            get {
                return ResourceManager.GetString("STEP_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   공정수율과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STEP_YIELD {
            get {
                return ResourceManager.GetString("STEP_YIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   공정간격시간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TACT_TIME {
            get {
                return ResourceManager.GetString("TACT_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   소요시간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TIME {
            get {
                return ResourceManager.GetString("TIME", resourceCulture);
            }
        }
    }
}
