//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APSWinForm.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceAPI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceAPI() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APSWinForm.Properties.ResourceAPI", typeof(ResourceAPI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   api/Account/UserInfo과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ACCOUNT_CUR_INFO {
            get {
                return ResourceManager.GetString("ACCOUNT_CUR_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/Account/Login과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ACCOUNT_LOGIN {
            get {
                return ResourceManager.GetString("ACCOUNT_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/Account/Logout과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ACCOUNT_LOGOUT {
            get {
                return ResourceManager.GetString("ACCOUNT_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/Account/Register과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ACCOUNT_REGISTER {
            get {
                return ResourceManager.GetString("ACCOUNT_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/Auth/GetAuth과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AUTH_LIST {
            get {
                return ResourceManager.GetString("AUTH_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/Auth/AuthSave과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AUTH_SAVE {
            get {
                return ResourceManager.GetString("AUTH_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/Data/all과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DATA_LIST {
            get {
                return ResourceManager.GetString("DATA_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/Data/Conn과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DATA_TABLE_CONN {
            get {
                return ResourceManager.GetString("DATA_TABLE_CONN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/Demand/Delete/{0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DEMAND_DELETE {
            get {
                return ResourceManager.GetString("DEMAND_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/Demand/AllList과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DEMAND_LIST {
            get {
                return ResourceManager.GetString("DEMAND_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/Demand/SaveDemand과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DEMAND_SAVE {
            get {
                return ResourceManager.GetString("DEMAND_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/EQUIPMENT/DelEQPARR과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EQP_ARRANGE_DELETE {
            get {
                return ResourceManager.GetString("EQP_ARRANGE_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/EQUIPMENT/ARRlist과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EQP_ARRANGE_LIST {
            get {
                return ResourceManager.GetString("EQP_ARRANGE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/EQUIPMENT/EQPArrnew과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EQP_ARRANGE_SAVE {
            get {
                return ResourceManager.GetString("EQP_ARRANGE_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/EQUIPMENT/DelEQP/{0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EQUIPMENT_DELETE {
            get {
                return ResourceManager.GetString("EQUIPMENT_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/EQUIPMENT/EQPlist과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EQUIPMENT_LIST {
            get {
                return ResourceManager.GetString("EQUIPMENT_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/EQUIPMENT/EQPnew과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EQUIPMENT_SAVE {
            get {
                return ResourceManager.GetString("EQUIPMENT_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/LineInfo/Delete/{0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LINE_INFO_DELETE {
            get {
                return ResourceManager.GetString("LINE_INFO_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/LineInfo/AllList과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LINE_INFO_LIST {
            get {
                return ResourceManager.GetString("LINE_INFO_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/LineInfo/SaveLineInfo과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LINE_INFO_SAVE {
            get {
                return ResourceManager.GetString("LINE_INFO_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/Product/Delete/{0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PRODUCT_DELETE {
            get {
                return ResourceManager.GetString("PRODUCT_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/Product/Products과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PRODUCT_LIST {
            get {
                return ResourceManager.GetString("PRODUCT_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/Product/SaveProduct과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PRODUCT_SAVE {
            get {
                return ResourceManager.GetString("PRODUCT_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/Result/EQPGantt/Common과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RESULT_EQP_COMMON {
            get {
                return ResourceManager.GetString("RESULT_EQP_COMMON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/Result/EQPGantt/Data과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RESULT_EQP_DATA {
            get {
                return ResourceManager.GetString("RESULT_EQP_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/Result/getLOTCategory과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RESULT_LOT_CATEGORY {
            get {
                return ResourceManager.GetString("RESULT_LOT_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/Result/getComboList과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RESULT_LOT_CBO {
            get {
                return ResourceManager.GetString("RESULT_LOT_CBO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/Result/getLOTList과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RESULT_LOT_LIST {
            get {
                return ResourceManager.GetString("RESULT_LOT_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/Result/Utilization/Common과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RESULT_UTIL_COMMON {
            get {
                return ResourceManager.GetString("RESULT_UTIL_COMMON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/Result/Utilization/Data과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RESULT_UTIL_DATA {
            get {
                return ResourceManager.GetString("RESULT_UTIL_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/SETUP_TIME/DelSetup과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SETUP_TIME_DELETE {
            get {
                return ResourceManager.GetString("SETUP_TIME_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/SETUP_TIME/SetupList과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SETUP_TIME_LIST {
            get {
                return ResourceManager.GetString("SETUP_TIME_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/SETUP_TIME/SetupNew과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SETUP_TIME_SAVE {
            get {
                return ResourceManager.GetString("SETUP_TIME_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/Step/DelStepInfo/{0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STD_STEP_INFO_DELETE {
            get {
                return ResourceManager.GetString("STD_STEP_INFO_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/Step/getStepInfoList과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STD_STEP_INFO_LIST {
            get {
                return ResourceManager.GetString("STD_STEP_INFO_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/Step/saveStdStep과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STD_STEP_INFO_SAVE {
            get {
                return ResourceManager.GetString("STD_STEP_INFO_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/Step/DelStepRoute?PROCESS_ID={0}&amp;STEP_ID={1}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STEP_ROUTE_DELETE {
            get {
                return ResourceManager.GetString("STEP_ROUTE_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/Step/getStepRouteList과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STEP_ROUTE_LIST {
            get {
                return ResourceManager.GetString("STEP_ROUTE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/Step/saveStepRoute과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STEP_ROUTE_SAVE {
            get {
                return ResourceManager.GetString("STEP_ROUTE_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/UserInfo/{0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string USER_INFO_BY_ID {
            get {
                return ResourceManager.GetString("USER_INFO_BY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/UserInfo/Delete/{0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string USER_INFO_DELETE {
            get {
                return ResourceManager.GetString("USER_INFO_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/UserInfo/AllList과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string USER_INFO_LIST {
            get {
                return ResourceManager.GetString("USER_INFO_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   api/UserInfo/UserInfoUpdate과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string USER_INFO_UPDATE {
            get {
                return ResourceManager.GetString("USER_INFO_UPDATE", resourceCulture);
            }
        }
    }
}
